# Generated by Django 5.0.1 on 2024-01-12 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="color",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="seller",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
